/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GalleriRouteImport } from './routes/galleri'
import { Route as DekorationRouteImport } from './routes/dekoration'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriRoute = GalleriRouteImport.update({
  id: '/galleri',
  path: '/galleri',
  getParentRoute: () => rootRouteImport,
} as any)
const DekorationRoute = DekorationRouteImport.update({
  id: '/dekoration',
  path: '/dekoration',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/dekoration': typeof DekorationRoute
  '/galleri': typeof GalleriRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/dekoration': typeof DekorationRoute
  '/galleri': typeof GalleriRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/dekoration': typeof DekorationRoute
  '/galleri': typeof GalleriRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catering'
    | '/dekoration'
    | '/galleri'
    | '/kontakt'
    | '/om-oss'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catering'
    | '/dekoration'
    | '/galleri'
    | '/kontakt'
    | '/om-oss'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/catering'
    | '/dekoration'
    | '/galleri'
    | '/kontakt'
    | '/om-oss'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CateringRoute: typeof CateringRoute
  DekorationRoute: typeof DekorationRoute
  GalleriRoute: typeof GalleriRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleri': {
      id: '/galleri'
      path: '/galleri'
      fullPath: '/galleri'
      preLoaderRoute: typeof GalleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dekoration': {
      id: '/dekoration'
      path: '/dekoration'
      fullPath: '/dekoration'
      preLoaderRoute: typeof DekorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CateringRoute: CateringRoute,
  DekorationRoute: DekorationRoute,
  GalleriRoute: GalleriRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
